### ISSUE TITLE
Suggest information element to profile should be possible with 'id' only

### ISSUE THREAD

**Issue by agisbrec** [HIIT/dime-server#81]
I'm trying to suggest new information elements to a profile. This requires a json of the form:
`{
  "informationelement": {
      "@type": "Document",
      "id": 728,
  },
  "weight": 0.22,
  "actor": "FooAlgorithm"
}`

Now I'm storing only "id" field of the documents and can't create such a json due to missing "@type" field. There a several options on how to fix this: 1) I store also the "@type" field. 2) I retrieve the information element from DiMe with the "id" and submit the correct "@type" field. 3) I submit "Document" for every information element (what happens if this doesn't match with DiMe?) 4) DiMe allows to specify the information elements by "id" only and checks internally for the other fields.

Is it possible to have the option 4)?

**Comment by mvsjober** [comment]
I believe it is required to specify the type because of Java's strict type system. Option 3) doesn't work in general since the correct type might not be a subtype of `Document`. However specifying `InformationElement` as the type works, since that is the parent type of any object that could be in that field. So you can use option 3b):

Submit "informationelement" like: 

    { 
        "@type": "InformationElement", 
        "id": 728
    }

I just tested it and it seems to work, see this script: https://github.com/HIIT/dime-server/blob/master/scripts/suggest-event.py.
